### ISSUE TITLE
TypeError: user.then is not a function

### ISSUE THREAD

**Issue by jtomaszon** [sahat/megaboilerplate#110]
**Configuration**:

- Platform:
  - [x] Node.js
- Framework:
  - [x] Express
  - [x] Angular 1.x
- Database:
  - [x] SQLite
- Template engine:
  - [x] Jade
- CSS framework:
  - [x] Bootstrap

**System:**
 - OS: MacOS
 - Arch: x86_64

I'm trying to update "My profile" and receive this error:
`TypeError: user.then is not a function`

This happen when create a user or even log in with Facebook..

**Comment by sahat** [comment]
@jtomaszon Can you post an error stack trace so I can see where the error is happening?

**Comment by jtomaszon** [comment]
`TypeError: user.then is not a function
    at exports.accountPut (/Users/jzon/Downloads/megaboilerplate-app/controllers/user.js:130:10)
    at Layer.handle [as handle_request] (/Users/jzon/Downloads/megaboilerplate-app/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/jzon/Downloads/megaboilerplate-app/node_modules/express/lib/router/route.js:131:13)
    at exports.ensureAuthenticated (/Users/jzon/Downloads/megaboilerplate-app/controllers/user.js:25:5)
    at Layer.handle [as handle_request] (/Users/jzon/Downloads/megaboilerplate-app/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/jzon/Downloads/megaboilerplate-app/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/jzon/Downloads/megaboilerplate-app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/jzon/Downloads/megaboilerplate-app/node_modules/express/lib/router/layer.js:95:5)
    at /Users/jzon/Downloads/megaboilerplate-app/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/Users/jzon/Downloads/megaboilerplate-app/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/jzon/Downloads/megaboilerplate-app/node_modules/express/lib/router/index.js:271:10)
    at null.<anonymous> (/Users/jzon/Downloads/megaboilerplate-app/server.js:50:9)
    at tryCatcher (/Users/jzon/Downloads/megaboilerplate-app/node_modules/bookshelf/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/jzon/Downloads/megaboilerplate-app/node_modules/bookshelf/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/jzon/Downloads/megaboilerplate-app/node_modules/bookshelf/node_modules/bluebird/js/main/promise.js:581:18)
    at Async._drainQueue (/Users/jzon/Downloads/megaboilerplate-app/node_modules/bookshelf/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/Users/jzon/Downloads/megaboilerplate-app/node_modules/bookshelf/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/jzon/Downloads/megaboilerplate-app/node_modules/bookshelf/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
`

**Comment by Mindful-Design** [comment]
How come this was this closed without a response? I have the same issue atm. :)
