### ISSUE TITLE
replaceCode FAILED: build,app,karma.conf.js

### ISSUE THREAD

**Issue by andreas-marschke** [sahat/megaboilerplate#134]
##### :boom: Error Stack Trace
```js
Error: replaceCode FAILED: build,app,karma.conf.js
    at _callee9$ (utils.js:469:11)
    at tryCatch (/app/node_modules/regenerator-runtime/runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/app/node_modules/regenerator-runtime/runtime.js:336:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/app/node_modules/regenerator-runtime/runtime.js:95:21)
    at step (utils.js:2:1)
    at utils.js:2:1
    at Promise._execute (/app/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/app/node_modules/bluebird/js/release/promise.js:473:18)
    at new Promise (/app/node_modules/bluebird/js/release/promise.js:77:14)
    at utils.js:2:1
    at replaceCodeMemory (/app/generators/utils.js:490:16)
    at _callee$ (generateTestingMocha.js:4:16)
    at tryCatch (/app/node_modules/regenerator-runtime/runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/app/node_modules/regenerator-runtime/runtime.js:336:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/app/node_modules/regenerator-runtime/runtime.js:95:21)
    at step (generateTestingMocha.js:2:1)
```

**Comment by sahat** [comment]
@andreas-marschke What were the exact choices you have selected so I can try to reproduce the issue on my machine?

**Comment by andreas-marschke** [comment]
@sahat 
I tested this on initially on my mobile device but was able to repro this on my laptop too. Sorry about the delay.

Setting was:
 - node.js
 - express
 - nunjucks
 - less
 - angularjs
 - no build tool (Grunt not available 😢 )
 - mocha
 - mongodb
 - email
 - no deployment (I just want to test this locally)

Good luck!
