### ISSUE TITLE
replaceCode FAILED: build,app,karma.conf.js

### ISSUE THREAD

**Issue by grishchenkoa** [sahat/megaboilerplate#139]
##### :boom: Error Stack Trace
```js
Error: replaceCode FAILED: build,app,karma.conf.js
    at _callee9$ (utils.js:469:11)
    at tryCatch (/app/node_modules/regenerator-runtime/runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/app/node_modules/regenerator-runtime/runtime.js:336:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/app/node_modules/regenerator-runtime/runtime.js:95:21)
    at step (utils.js:2:1)
    at utils.js:2:1
    at Promise._execute (/app/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/app/node_modules/bluebird/js/release/promise.js:475:18)
    at new Promise (/app/node_modules/bluebird/js/release/promise.js:77:14)
    at utils.js:2:1
    at replaceCodeMemory (/app/generators/utils.js:490:16)
    at _callee$ (generateTestingJasmine.js:4:16)
    at tryCatch (/app/node_modules/regenerator-runtime/runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/app/node_modules/regenerator-runtime/runtime.js:336:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/app/node_modules/regenerator-runtime/runtime.js:95:21)
    at step (generateTestingJasmine.js:2:1)
```

**Comment by sahat** [comment]
Should be fixed now. It was an issue with incorrect `karma.conf.js` path.
