### ISSUE TITLE
erro at run "npm run start"

### ISSUE THREAD

**Issue by raisiqueira** [sahat/megaboilerplate#159]
```
 hidden-cherry@1.0.0 start /home/rai/Projetos/megaboilesqlite
> node server.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at Server.listen (net.js:1385:5)
    at EventEmitter.listen (/home/rai/Projetos/megaboilesqlite/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/home/rai/Projetos/megaboilesqlite/server.js:86:5)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3

npm ERR! Linux 4.4.0-28-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "start"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! hidden-cherry@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hidden-cherry@1.0.0 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hidden-cherry package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hidden-cherry
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hidden-cherry
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/rai/Projetos/megaboilesqlite/npm-debug.log
 ▲  rai@rslinux ~/P/megaboilesqlite  $                        
```

**Comment by sahat** [comment]
@raisiqueira That's a very common node.js error where you already have an existing app running on port 3000. Either kill that app to free up the port or change port 3000 to something else, e.g. 4000 in `server.js`.
