### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Insidebox** [sahat/megaboilerplate#201]
GET / 500 7.523 ms - -
TypeError: Cannot read property 'picture' of undefined
    at Header.render (/Users/insidebox/GitHub/reactbox/app/components/Header.js:18:23)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/Users/insidebox/GitHub/reactbox/node_modules/react/lib/ReactCompositeComponent.js:815:34)
    at ReactCompositeComponentWrapper._renderValidatedComponent (/Users/insidebox/GitHub/reactbox/node_modules/react/lib/ReactCompositeComponent.js:841:32)
    at ReactCompositeComponentWrapper.performInitialMount (/Users/insidebox/GitHub/reactbox/node_modules/react/lib/ReactCompositeComponent.js:351:30)
    at ReactCompositeComponentWrapper.mountComponent (/Users/insidebox/GitHub/reactbox/node_modules/react/lib/ReactCompositeComponent.js:244:21)
    at Object.mountComponent (/Users/insidebox/GitHub/reactbox/node_modules/react/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (/Users/insidebox/GitHub/reactbox/node_modules/react/lib/ReactCompositeComponent.js:357:34)
    at ReactCompositeComponentWrapper.mountComponent (/Users/insidebox/GitHub/reactbox/node_modules/react/lib/ReactCompositeComponent.js:244:21)
    at Object.mountComponent (/Users/insidebox/GitHub/reactbox/node_modules/react/lib/ReactReconciler.js:46:35)
    at ReactDOMComponent.mountChildren (/Users/insidebox/GitHub/reactbox/node_modules/react/lib/ReactMultiChild.js:215:44)
    at ReactDOMComponent._createContentMarkup (/Users/insidebox/GitHub/reactbox/node_modules/react/lib/ReactDOMComponent.js:611:32)
    at ReactDOMComponent.mountComponent (/Users/insidebox/GitHub/reactbox/node_modules/react/lib/ReactDOMComponent.js:493:29)
    at Object.mountComponent (/Users/insidebox/GitHub/reactbox/node_modules/react/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (/Users/insidebox/GitHub/reactbox/node_modules/react/lib/ReactCompositeComponent.js:357:34)
    at ReactCompositeComponentWrapper.mountComponent (/Users/insidebox/GitHub/reactbox/node_modules/react/lib/ReactCompositeComponent.js:244:21)
    at Object.mountComponent (/Users/insidebox/GitHub/reactbox/node_modules/react/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (/Users/insidebox/GitHub/reactbox/node_modules/react/lib/ReactCompositeComponent.js:357:34)
    at ReactCompositeComponentWrapper.mountComponent (/Users/insidebox/GitHub/reactbox/node_modules/react/lib/ReactCompositeComponent.js:244:21)
    at Object.mountComponent (/Users/insidebox/GitHub/reactbox/node_modules/react/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (/Users/insidebox/GitHub/reactbox/node_modules/react/lib/ReactCompositeComponent.js:357:34)
    at ReactCompositeComponentWrapper.mountComponent (/Users/insidebox/GitHub/reactbox/node_modules/react/lib/ReactCompositeComponent.js:244:21)
    at Object.mountComponent (/Users/insidebox/GitHub/reactbox/node_modules/react/lib/ReactReconciler.js:46:35)
GET / 500 7.283 ms - -
TypeError: Cannot read property 'picture' of undefined
    at Header.render (/Users/insidebox/GitHub/reactbox/app/components/Header.js:18:23)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/Users/insidebox/GitHub/reactbox/node_modules/react/lib/ReactCompositeComponent.js:815:34)
    at ReactCompositeComponentWrapper._renderValidatedComponent (/Users/insidebox/GitHub/reactbox/node_modules/react/lib/ReactCompositeComponent.js:841:32)
    at ReactCompositeComponentWrapper.performInitialMount (/Users/insidebox/GitHub/reactbox/node_modules/react/lib/ReactCompositeComponent.js:351:30)
    at ReactCompositeComponentWrapper.mountComponent (/Users/insidebox/GitHub/reactbox/node_modules/react/lib/ReactCompositeComponent.js:244:21)
    at Object.mountComponent (/Users/insidebox/GitHub/reactbox/node_modules/react/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (/Users/insidebox/GitHub/reactbox/node_modules/react/lib/ReactCompositeComponent.js:357:34)
    at ReactCompositeComponentWrapper.mountComponent (/Users/insidebox/GitHub/reactbox/node_modules/react/lib/ReactCompositeComponent.js:244:21)
    at Object.mountComponent (/Users/insidebox/GitHub/reactbox/node_modules/react/lib/ReactReconciler.js:46:35)
    at ReactDOMComponent.mountChildren (/Users/insidebox/GitHub/reactbox/node_modules/react/lib/ReactMultiChild.js:215:44)
    at ReactDOMComponent._createContentMarkup (/Users/insidebox/GitHub/reactbox/node_modules/react/lib/ReactDOMComponent.js:611:32)
    at ReactDOMComponent.mountComponent (/Users/insidebox/GitHub/reactbox/node_modules/react/lib/ReactDOMComponent.js:493:29)
    at Object.mountComponent (/Users/insidebox/GitHub/reactbox/node_modules/react/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (/Users/insidebox/GitHub/reactbox/node_modules/react/lib/ReactCompositeComponent.js:357:34)
    at ReactCompositeComponentWrapper.mountComponent (/Users/insidebox/GitHub/reactbox/node_modules/react/lib/ReactCompositeComponent.js:244:21)
    at Object.mountComponent (/Users/insidebox/GitHub/reactbox/node_modules/react/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (/Users/insidebox/GitHub/reactbox/node_modules/react/lib/ReactCompositeComponent.js:357:34)
    at ReactCompositeComponentWrapper.mountComponent (/Users/insidebox/GitHub/reactbox/node_modules/react/lib/ReactCompositeComponent.js:244:21)
    at Object.mountComponent (/Users/insidebox/GitHub/reactbox/node_modules/react/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (/Users/insidebox/GitHub/reactbox/node_modules/react/lib/ReactCompositeComponent.js:357:34)
    at ReactCompositeComponentWrapper.mountComponent (/Users/insidebox/GitHub/reactbox/node_modules/react/lib/ReactCompositeComponent.js:244:21)
    at Object.mountComponent (/Users/insidebox/GitHub/reactbox/node_modules/react/lib/ReactReconciler.js:46:35)
GET / 500 4.283 ms - -

**Comment by lusa** [comment]
I was able to fix this by clearing my cookies. Ran into this because I deleted the database then tried to access the app again.
