### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by niallobrien** [sahat/megaboilerplate#66]
After cloning this repo and `npm i && npm start` I get the below message on startup. I'm running node v6 with npm v3.

```
{ Error: ENOENT: no such file or directory, open '.env'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at Object.module.exports.config (/private/var/application/my_projects/boilerplate/node_modules/dotenv/lib/main.js:30:37)
    at Object.<anonymous> (/private/var/application/my_projects/boilerplate/server.js:15:8)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:445:3 errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
Express server listening on port 4000
```

**Comment by sahat** [comment]
I will need to add try catch around dotenv.load(). The only thing that won't work without .env  is file upload to Azure Storage.
